package src.cliente;

import uteis.DragListener;
import uteis.JTextFieldLimit;
import java.awt.Color;
import java.io.IOException;
import javax.swing.JOptionPane;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author wagui
 */
public class LoginForm extends javax.swing.JFrame {
    
    Cliente cliente;
    JSONObject jsonObj;
    JSONParser parser = new JSONParser();
    
    /**
     * Creates new form NewJFrame
     */
    public LoginForm(Cliente cliente) {
        this.cliente = cliente;
        initComponents();
        txtSenha.setDocument(new JTextFieldLimit(6));
        setTitle("Acessar sistema");        
        DragListener drag = new DragListener();
        addMouseListener(drag);
        addMouseMotionListener(drag);
    }
    
    public void setCpf(String cpf) {
        txtCpf.setText(cpf);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        SeparatorSenha = new javax.swing.JSeparator();
        lblCpf = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        SeparatorCpf = new javax.swing.JSeparator();
        lblSenha = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblFechar = new javax.swing.JLabel();
        lblCadastrar = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setUndecorated(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(130, 170, 227));
        jPanel1.setMinimumSize(new java.awt.Dimension(370, 490));

        jLabel1.setBackground(new java.awt.Color(102, 255, 255));
        jLabel1.setFont(new java.awt.Font("Liberation Serif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(234, 253, 252));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Triagem Médica");

        jLabel2.setBackground(new java.awt.Color(102, 255, 255));
        jLabel2.setFont(new java.awt.Font("Constantia", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(234, 253, 252));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Identifique-se para acessar o sistema");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        jPanel3.setBackground(new java.awt.Color(191, 234, 245));
        jPanel3.setMinimumSize(new java.awt.Dimension(370, 490));
        jPanel3.setPreferredSize(new java.awt.Dimension(370, 490));

        btnLogin.setBackground(new java.awt.Color(130, 170, 227));
        btnLogin.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(234, 253, 252));
        btnLogin.setText("Logar");
        btnLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(234, 253, 252), 1, true));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        SeparatorSenha.setForeground(new java.awt.Color(145, 216, 228));

        lblCpf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCpf.setForeground(new java.awt.Color(130, 170, 227));
        lblCpf.setText("CPF");

        txtSenha.setBackground(new java.awt.Color(191, 234, 245));
        txtSenha.setForeground(new java.awt.Color(30, 80, 137));
        txtSenha.setBorder(null);
        txtSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSenhaFocusLost(evt);
            }
        });

        SeparatorCpf.setForeground(new java.awt.Color(130, 170, 227));

        lblSenha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(145, 216, 228));
        lblSenha.setText("Senha");

        jLabel12.setForeground(new java.awt.Color(130, 170, 227));
        jLabel12.setText("Não possui cadastro?");

        lblFechar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFechar.setForeground(new java.awt.Color(51, 51, 51));
        lblFechar.setText("x");
        lblFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFecharMouseClicked(evt);
            }
        });

        lblCadastrar.setForeground(new java.awt.Color(102, 102, 102));
        lblCadastrar.setText("Cadastrar");
        lblCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCadastrarMouseClicked(evt);
            }
        });

        txtCpf.setBackground(new java.awt.Color(191, 234, 245));
        txtCpf.setBorder(null);
        txtCpf.setForeground(new java.awt.Color(30, 80, 137));
        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCpfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCpfFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(lblFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCadastrar)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblCpf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(219, 219, 219))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, 0)
                                .addComponent(SeparatorCpf))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(206, 206, 206))
                            .addComponent(txtSenha)
                            .addComponent(SeparatorSenha)
                            .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCpf))
                        .addGap(60, 60, 60))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133)
                .addComponent(lblCpf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(SeparatorCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblSenha)
                .addGap(4, 4, 4)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(SeparatorSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        //Coletando entradas
        String cpf = txtCpf.getText().replace("-", "").replace(".", "");
        String senha = String.valueOf(txtSenha.getPassword());      
        
                
        //Verificando se entradas não são vazias
        if(cpf.isBlank() || senha.isBlank()) {
            JOptionPane.showMessageDialog(
                rootPane,
                "Por favor, preencha todos os campos",
                "Tente novamente",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        //Cria o JSON e coloca as entradas
        jsonObj = new JSONObject();        
        jsonObj.put("code", 3);
        jsonObj.put("cpf", cpf);
        jsonObj.put("password", senha);
        System.out.println("JSON criada: " + jsonObj.toJSONString());
        
        try {            
            //Envia a mensagem pro server e aguarda a resposta
            String msgServer = cliente.enviaMensagem(jsonObj.toJSONString());      
            //Log da resposta
            cliente.clienteLog.atualizaLog("Recebeu: " + msgServer);
            
            //Interpreta a mensagem do server
            jsonObj = new JSONObject();
            jsonObj = (JSONObject) parser.parse(msgServer);                            
            
            if(String.valueOf(jsonObj.get("status")).equals("true")) {
                                
                //Confere se é medico ou paciente
                JSONObject userObj = (JSONObject) jsonObj.get("user");
                if(String.valueOf(userObj.get("doctor")).equals("true")) {                   
                    new DoutorTela(cliente, cpf).setVisible(true);                    
                    this.dispose();
                } else {                    
                    new TriagemForm(cliente,cpf).setVisible(true);                    
                    this.dispose();
                }
                                
            } else {
                
                JOptionPane.showMessageDialog(
                rootPane,
                "CPF ou Senha incorretos",
                "Tente novamente",
                JOptionPane.ERROR_MESSAGE
                );                
            }
            
        } catch (IOException ex) {
            System.out.println("Mensagem não enviada");
        } catch (ParseException ex) {
            System.out.println("Erro ao criar Json");
        } 
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusGained
        SeparatorSenha.setForeground(new Color(130,170,227));
        lblSenha.setForeground(new Color(130,170,227));
    }//GEN-LAST:event_txtSenhaFocusGained

    private void txtSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusLost
        SeparatorSenha.setForeground(new Color(145,216,228));
        lblSenha.setForeground(new Color(145,216,228));
    }//GEN-LAST:event_txtSenhaFocusLost

    private void lblFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseClicked
        // TODO add your handling code here:
        dispose();
        System.exit(0);
    }//GEN-LAST:event_lblFecharMouseClicked

    private void lblCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCadastrarMouseClicked
        // TODO add your handling code here:
        new RegistroForm(cliente, this).setVisible(true);
        dispose();
    }//GEN-LAST:event_lblCadastrarMouseClicked

    private void txtCpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpfFocusGained
        SeparatorCpf.setForeground(new Color(130,170,227));
        lblCpf.setForeground(new Color(130,170,227));
    }//GEN-LAST:event_txtCpfFocusGained

    private void txtCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCpfFocusLost
        SeparatorCpf.setForeground(new Color(145,216,228));
        lblCpf.setForeground(new Color(145,216,228));
    }//GEN-LAST:event_txtCpfFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator SeparatorCpf;
    private javax.swing.JSeparator SeparatorSenha;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCadastrar;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblFechar;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
