package src.server;

import java.io.IOException;
import javax.swing.DefaultListModel;

/**
 *
 * @author wagui
 */
public class ServerTela extends javax.swing.JFrame {
       
    public ServerTela() throws IOException {
        super("Registro de eventos servidor");
        initComponents();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtInfo = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        listUsuarios = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        listPacientes = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(740, 467));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel3.setMaximumSize(new java.awt.Dimension(500, 2147483647));
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 470));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setMaximumSize(new java.awt.Dimension(2147483647, 300));
        jPanel2.setMinimumSize(new java.awt.Dimension(100, 200));
        jPanel2.setPreferredSize(new java.awt.Dimension(234, 200));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane3.setMaximumSize(new java.awt.Dimension(32767, 200));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(234, 86));

        txtInfo.setEditable(false);
        txtInfo.setColumns(20);
        txtInfo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtInfo.setRows(5);
        txtInfo.setText("Informações do servidor:\n\n");
        jScrollPane3.setViewportView(txtInfo);

        jPanel2.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jButton1.setText("Desligar");
        jButton1.setBorder(null);
        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1.setMaximumSize(new java.awt.Dimension(200, 50));
        jButton1.setMinimumSize(new java.awt.Dimension(100, 25));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, java.awt.BorderLayout.PAGE_END);

        jPanel3.add(jPanel2);

        jScrollPane4.setMaximumSize(new java.awt.Dimension(32767, 300));

        listUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        listUsuarios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Lista de Usúarios:" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listUsuarios.setEnabled(false);
        jScrollPane4.setViewportView(listUsuarios);

        jPanel3.add(jScrollPane4);

        jScrollPane5.setMaximumSize(new java.awt.Dimension(32767, 300));

        listPacientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        listPacientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Fila de Pacientes:" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listPacientes.setEnabled(false);
        jScrollPane5.setViewportView(listPacientes);

        jPanel3.add(jScrollPane5);

        getContentPane().add(jPanel3);

        jPanel1.setPreferredSize(new java.awt.Dimension(100, 200));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBorder(null);

        txtLog.setEditable(false);
        txtLog.setColumns(20);
        txtLog.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtLog.setRows(5);
        txtLog.setText("Troca de mensagens (Log):\n\n");
        jScrollPane2.setViewportView(txtLog);

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed
        
    public void atualizaLog(String texto) {
        txtLog.append(texto + "\n");
    }
    
    public void atualizaUsuarios(String[] usuarioLista) {        
        
        DefaultListModel listModel = new DefaultListModel();
        listModel.addElement("Usúarios conectados:");
        for (int i = 0; i < usuarioLista.length; i++) {
            listModel.addElement(i+1 + ": " + usuarioLista[i]);
        }
        
        listUsuarios.setModel(listModel);               
    }
    
    public void atualizaPacientes(String[] pacienteLista) {        
        
        DefaultListModel listModel = new DefaultListModel();
        listModel.addElement("Lista de pacientes:");
        for (int i = 0; i < pacienteLista.length; i++) {
            listModel.addElement(i+1 + ": " + pacienteLista[i]);
        }
        
        listPacientes.setModel(listModel);               
    }
    
    public void atualizainfo(int porta, String endereco, String data) {        
        txtInfo.append("Endereço: " + endereco + "\n");
        txtInfo.append("Porta: " + porta + "\n");
        txtInfo.append("Aberto em: " + data + "\n");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<String> listPacientes;
    private javax.swing.JList<String> listUsuarios;
    private javax.swing.JTextArea txtInfo;
    private javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables
}
